site_name: Myth Docs
site_url: http://localhost:8000
theme:
  name: material
markdown_extensions:
  - footnotes
nav:
  - Home: index.md
  - Tags: tags.md
  - Scripting: scripting.md
  - Collections: collections.md
  - Sounds: sounds.md
