site_name: Myth Mapmaking Docs
site_url: https://jwheare.github.io/mythdocs/
# repo_url: https://github.com/jwheare/mythdocs
# repo_name: jwheare/mythdocs
copyright: Copyright &copy; James Wheare
extra_css:
  - css/extra.css

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/Smuv2tk5f6
      name: Project Magma - Myth Mapmaking Discord
    - icon: fontawesome/brands/github 
      link: https://github.com/jwheare/mythdocs
      name: Source code on Github

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/sword-cross
  features:
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system color scheme

nav:
  - Home: index.md
  - Tags: tags.md
  - Scripting: scripting.md
  - Collections: collections.md
  - Sounds: sounds.md
  - Models: models.md
